/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import obesenec.Ukladanie;
import enumy.Farba;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import ponuka.NovaHra;
import ponuka.Skore;

/**
 *
 * @author Miloš
 */
public class HlavneMenu extends javax.swing.JFrame {
    private  Skore skore;
    private boolean pravda = true;
    private Color color;
    /**
     * Creates new form HlavneMenu
     */
    public HlavneMenu() throws IOException {
        ImageIcon icon = new ImageIcon("src/obrazky/ikony/ikona.png");
        super.setIconImage(icon.getImage());
        //pokial nenačíta žiaden súbor tak vytvorí novú inštanciu triedy skore
        try {
            if (Ukladanie.nacitaj() == null) {
                this.skore = new Skore();
            } else {
                this.skore = Ukladanie.nacitaj();
            }
        } catch (FileNotFoundException | ClassNotFoundException ex) {
            Logger.getLogger(HlavneMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        super.setVisible(false);
        this.initComponents();
    }
    
    public void zobraz() throws InterruptedException {
        super.setLocationRelativeTo(null);
        super.setVisible(true);
        this.animacia();
    }
    
    
    public void skry() {
        super.setVisible(false);
    }
    
    /**
     * úvodná krátka animácia ktorá funguje len pri prvom spustení
     */
    private void animacia() throws InterruptedException {
        int i = 1;
        while (i <= 7) {
            this.jLabel2.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/obrazky/animacia/" + i + ".png"))));
            Thread.sleep(500);
            i++;
        }    
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanel jPanel2 = new JPanel();
        JButton jButton4 = new JButton();
        JButton jButton5 = new JButton();
        JButton jButton6 = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton jButton1 = new JButton();
        JButton jButton7 = new JButton();
        JButton jButton2 = new JButton();
        JPanel jPanel3 = new JPanel();
        jLabel2 = new javax.swing.JLabel();
        JScrollPane jScrollPane1 = new JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obesenec");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setBackground(new java.awt.Color(51, 255, 0));
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setBackground(new java.awt.Color(0, 51, 255));
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Skore");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Nova Hra");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ukončiť");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton7)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(490, 20, 250, 400);

        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("jjLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 470, 400);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 420, 350);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 470, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jPanel1.setBackground(Farba.CERVENA.getFarba());
        this.color = Farba.CERVENA.getFarba();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.jPanel1.setBackground(Farba.ZELENA.getFarba());
        this.color = Farba.ZELENA.getFarba();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jPanel1.setBackground(Farba.MODRA.getFarba());
        this.color = Farba.MODRA.getFarba();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // po kliknutí tlačidla skryje label a zobrazí plochu s načítaným skore
        if (!this.pravda) {
            this.jTextArea1.setVisible(false);
            this.jLabel2.setVisible(true);
            this.pravda = true;
        } else {
            this.jLabel2.setVisible(false);
            this.jTextArea1.setVisible(true);
            this.pravda = false;
        }
       
        this.jTextArea1.setText(this.skore.vypis());    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        NovaHra novaHra = new NovaHra(this.color, this.skore, this);
        novaHra.zobraz();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String []args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavneMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new HlavneMenu().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(HlavneMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables



}
